# Generated by Django 4.2 on 2023-08-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
