# Generated by Django 4.2 on 2023-08-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ingredients_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='measurement',
            field=models.CharField(default='measurement', max_length=100),
        ),
    ]
