# Generated by Django 4.2 on 2023-08-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_ingredients_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField(default='', max_length=250)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
        ),
    ]
