# Generated by Django 4.2 on 2023-08-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_ingredients_measurement_alter_ingredients_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directions',
            new_name='Direction',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
